version: "3.8"

services:
  api:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    image: bamboo-api
    container_name: bamboo-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: bamboo-mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_ROOT_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_ROOT_PASS
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
